name: Qt Qmake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

    # 设置Qt环境
- name: Install Qt on Windows
  run: |
    choco install qt --version=5.15.16 -y

    # 配置环境变量（确保路径包含Qt工具）
    - name: Add Qt to PATH
      run: |
        echo "C:\Qt\5.15.16\msvc2019_64\bin" >> $Env:Path
      shell: powershell

    # 运行qmake
    - name: Run Qmake
      run: qmake CONFIG+=release

    # 构建项目
    - name: Build
      run: nmake

    # 可选：运行测试
    - name: Run Tests
      run: .\tests\HideSlothQt.exe 