name: Qt QMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build on Windows
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'  # 5.15.16 not always available
          target: desktop
          arch: win64_msvc2019_64
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      #- name: Install OpenSSL
      #  run: choco install openssl --version=3.1.2 -y

      #- name: Set up OpenSSL Path
      #  run: |
      #    echo "C:\Program Files\OpenSSL-Win64\bin" >> $Env:GITHUB_PATH
      #  shell: powershell

      - name: Run qmake
        run: qmake CONFIG+=release

      - name: Build with nmake
        run: nmake

      - name: Run Tests
        run: .\tests\HideSlothQt.exe
        continue-on-error: true  # Optional if tests are not critical

  #build-linux:
  #  runs-on: ubuntu-latest
  #  name: Build on Linux
  #  steps:
  #    - name: Checkout source
  #      uses: actions/checkout@v3

  #    - name: Install Qt
  #      uses: jurplel/install-qt-action@v3
  #      with:
  #        version: '5.15.2'
  #        target: desktop
  #        arch: gcc_64

  #    - name: Install dependencies
  #      run: |
  #        sudo apt update
  #        sudo apt install -y build-essential libssl-dev libjpeg-dev

  #    - name: Run qmake
  #      run: qmake CONFIG+=release

  #    - name: Build with make
  #      run: make -j$(nproc)

  #    - name: Run Tests
  #      run: ./tests/HideSlothQt
  #      continue-on-error: true
